api:
  build: ./api
  command: bin/rails s -p 5000 -b 0.0.0.0
  working_dir: /api
  volumes:
    - ./api:/api
    - $HOME/.zsh_history:/root/.zsh_history
    - $HOME/.pry_history:/root/.pry_history
  volumes_from:
    - bundle
  links:
    - redis
    - postgres
  ports:
    - "5000:5000"
  environment:
    ZSH_THEME: lukerandall
    BUNDLE_JOBS: 20

frontend:
  build: ./frontend
  command: ember serve -p 4200 --live-reload-port 35729 --proxy http://api:5000
  working_dir: /frontend
  volumes:
    - ./frontend:/frontend
    - $HOME/.zsh_history:/root/.zsh_history
    - $HOME/.pry_history:/root/.pry_history
  links:
    - api
  ports:
    - "4200:4200"
    - "35729:35729"

postgres:
  image: postgres:9.5
  ports:
    - "5432"

redis:
  image: redis
  volumes:
    - ~/data/redis/t4b:/data
  ports:
    - "6379"

bundle:
  image: busybox
  volumes:
    - /bundle
